name: Build Dev Image Docker Image
on:
  workflow_run:
    workflows: ["Build Dev Image Nix Image"]
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - 'dev-images/docker/Dockerfile'
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/reusable-docker-image.yaml
    secrets: inherit
    with:
      image_name: dev-image
      image_tag: docker
      cache_scope: dev-image-docker
      context_path: dev-images/docker
      dockerfile: Dockerfile
