name: Build Dev Image Nix Image
on:
  workflow_run:
    workflows: ["Build Dev Image Base Image"]
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - 'dev-images/nix/Dockerfile'
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/reusable-docker-image.yaml
    secrets: inherit
    with:
      image_name: dev-image
      image_tag: nix
      cache_scope: dev-image-nix
      context_path: dev-images/nix
      dockerfile: Dockerfile
