name: Build Dev Image Full DinD Image
on:
  workflow_run:
    workflows: ["Build Dev Image Full Image"]
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - 'dev-images/full-dind/Dockerfile'
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/reusable-docker-image.yaml
    secrets: inherit
    with:
      image_name: dev-image
      image_tag: full-dind
      cache_scope: dev-image-full-dind
      context_path: dev-images/full-dind
      dockerfile: Dockerfile
