name: Build Dev Image Base Image
on:
  push:
    branches:
      - main
    paths:
      - 'dev-images/base/Dockerfile'
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/reusable-docker-image.yaml
    secrets: inherit
    with:
      image_name: dev-image
      image_tag: base
      cache_scope: dev-image-base
      context_path: dev-images/base
      dockerfile: Dockerfile
