name: Build Dev Image NodeJS Image
on:
  workflow_run:
    workflows: ["Build Dev Image Nix Image"]
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - 'dev-images/node/Dockerfile'
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/reusable-docker-image.yaml
    secrets: inherit
    with:
      image_name: dev-image
      image_tag: node
      cache_scope: dev-image-node
      context_path: dev-images/node
      dockerfile: Dockerfile
