name: Build Docker Flood Image

on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:
      inputs:
        skip_check:
          description: 'Skip build if image revision matches source?'
          required: true
          type: boolean
          default: true

jobs:
  call:
    uses: ./.github/workflows/reusable-docker-image.yaml
    secrets: inherit
    with:
      image_name: flood
      image_tag: latest
      skip_if_image_revision_matches_source: ${{ github.event.inputs.skip_check != 'false' }}
      cache_scope: flood
      source_repository: njzydark/flood
      source_ref: njzy
      context_from: source
      context_path: .
      dockerfile: flood/Dockerfile
      dockerfile_from: current
      platforms: 'linux/amd64'
