name: Build Hapi Image
on:
  push:
    branches:
      - main
    paths:
      - 'hapi/Dockerfile'
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/reusable-docker-image.yaml
    secrets: inherit
    with:
      image_name: hapi
      image_tag: latest
      cache_scope: hapi
      context_path: hapi
      dockerfile: Dockerfile
